name: Build DBCompare Executable

on:
  push:
    branches: [ develop ]  # actual branch name

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: Build executable
      run: pyinstaller --name=dbcompare --onefile --windowed --add-data "img/icon.png;." --icon="img/icon.png" main.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dbcompare-app
        path: dist/dbcompare.exe
